from typing import Protocol

from backend.domain.identity import ClaimantAuthSessionRecord, CustomerAccountRecord


class IdentityRepository(Protocol):
    def authenticate(self, email: str, password: str) -> CustomerAccountRecord | None: ...

    def get_account(self, customer_id: str) -> CustomerAccountRecord | None: ...

    def save_account(self, account: CustomerAccountRecord) -> None: ...

    def save_session(self, session: ClaimantAuthSessionRecord) -> None: ...

    def get_session(self, token_hash: str) -> ClaimantAuthSessionRecord | None: ...

    def revoke_session(self, token_hash: str) -> bool: ...
